package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.14 01:15:27 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class ElementtiTest {



  // Generated by ComTest BEGIN
  /** testElementti28 */
  @Test
  public void testElementti28() {    // Elementti: 28
    Elementti e1 = new Elementti(1, "testi", 2, 3); 
    Elementti e2 = new Elementti(2, "testi2", 5, 1); 
    assertEquals("From: Elementti line: 31", "testi", e1.getNimi()); assertEquals("From: Elementti line: 31", 1, e1.getID()); assertEquals("From: Elementti line: 31", 2, e1.getVahvuusID()); assertEquals("From: Elementti line: 31", 3, e1.getHeikkousID()); 
    assertEquals("From: Elementti line: 32", "testi2", e2.getNimi()); assertEquals("From: Elementti line: 32", 2, e2.getID()); 
    e1.setNimi("testitesti"); e1.setID(4); e1.setVahvuusID(1); e1.setHeikkousID(6); 
    assertEquals("From: Elementti line: 34", "testitesti", e1.getNimi()); assertEquals("From: Elementti line: 34", 4, e1.getID()); assertEquals("From: Elementti line: 34", 1, e1.getVahvuusID()); assertEquals("From: Elementti line: 34", 6, e1.getHeikkousID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testElementti52 */
  @Test
  public void testElementti52() {    // Elementti: 52
    Elementti vesi = new Elementti(" 1 |vesi         |2          |6"); 
    assertEquals("From: Elementti line: 54", "vesi", vesi.getNimi()); assertEquals("From: Elementti line: 54", 1, vesi.getID()); assertEquals("From: Elementti line: 54", 2, vesi.getVahvuusID()); assertEquals("From: Elementti line: 54", 6, vesi.getHeikkousID()); 
    Elementti tuli = new Elementti(" 2 | tuli|    32|testitesti"); 
    assertEquals("From: Elementti line: 56", "tuli", tuli.getNimi()); assertEquals("From: Elementti line: 56", 2, tuli.getID()); assertEquals("From: Elementti line: 56", 32, tuli.getVahvuusID()); assertEquals("From: Elementti line: 56", -1, tuli.getHeikkousID()); 
    Elementti maa = new Elementti("maa| 2|3"); 
    assertEquals("From: Elementti line: 58", null, maa.getNimi()); assertEquals("From: Elementti line: 58", 0, maa.getID()); assertEquals("From: Elementti line: 58", 0, maa.getVahvuusID()); assertEquals("From: Elementti line: 58", 0, maa.getHeikkousID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo165 */
  @Test
  public void testCompareTo165() {    // Elementti: 165
    Elementti e1 = new Elementti(1, "testi", 2, 3); 
    Elementti e2 = new Elementti(2, "testi2", 5, 1); 
    Elementti e4 = new Elementti(4, "testi4", 6, 5); 
    assertEquals("From: Elementti line: 169", 1, e1.compareTo(e2)); assertEquals("From: Elementti line: 169", -1, e2.compareTo(e1)); 
    assertEquals("From: Elementti line: 170", 0, e2.compareTo(e4)); assertEquals("From: Elementti line: 170", 0, e4.compareTo(e2)); 
    assertEquals("From: Elementti line: 171", 0, e4.compareTo(e1)); 
  } // Generated by ComTest END
}