package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.15 10:56:03 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ElementitTest {



  // Generated by ComTest BEGIN
  /** testEtsiElementti48 */
  @Test
  public void testEtsiElementti48() {    // Elementit: 48
    Elementit elementit = new Elementit(); 
    Elementti e1 = new Elementti(1, "testi", 2, 3); 
    assertEquals("From: Elementit line: 51", 0, elementit.getLkm()); 
    Elementti e2 = new Elementti(2, "testi2", 5, 1); 
    elementit.lisaa(e1); elementit.lisaa(e2); 
    assertEquals("From: Elementit line: 54", e2, elementit.etsiElementti(2)); 
    assertEquals("From: Elementit line: 55", e2.getID() - 1, elementit.etsiElementti(1).getID()); 
    assertEquals("From: Elementit line: 56", 2, elementit.getLkm()); 
  } // Generated by ComTest END
}