package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import java.util.ArrayList;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 12:53:53 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ElementitTest {



  // Generated by ComTest BEGIN
  /** testEtsiElementti63 */
  @Test
  public void testEtsiElementti63() {    // Elementit: 63
    Elementit elementit = new Elementit(); 
    Elementti e1 = new Elementti(1, "testi", 2, 3); 
    assertEquals("From: Elementit line: 66", 0, elementit.getLkm()); 
    Elementti e2 = new Elementti(2, "testi2", 5, 1); 
    elementit.lisaa(e1); elementit.lisaa(e2); 
    assertEquals("From: Elementit line: 69", e2, elementit.etsiElementti(2)); 
    assertEquals("From: Elementit line: 70", e2.getID() - 1, elementit.etsiElementti(1).getID()); 
    assertEquals("From: Elementit line: 71", 2, elementit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta103 
   * @throws IOException when error
   */
  @Test
  public void testLueTiedostosta103() throws IOException {    // Elementit: 103
    String tiedosto = "elementitTest.dat"; 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
    VertaaTiedosto.kirjoitaTiedosto(tiedosto, ";id|elementti    |vahvuusID  |heikkousID\n 1 |vesi         |2          |6\n 2 |tuli         |4          |1\n 3 |maa          |5          |4"); 
    Elementit el = new Elementit(tiedosto); 
    el.lueTiedostosta(); 
    assertEquals("From: Elementit line: 113", 3, el.getLkm()); 
    assertEquals("From: Elementit line: 114", "vesi", el.etsiElementti(1).getNimi()); 
    assertEquals("From: Elementit line: 115", 4, el.etsiElementti(2).getVahvuusID()); 
    assertEquals("From: Elementit line: 116", 4, el.etsiElementti(3).getHeikkousID()); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
  } // Generated by ComTest END
}