package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.14 17:09:23 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class ElementtiTest {



  // Generated by ComTest BEGIN
  /** testElementti26 */
  @Test
  public void testElementti26() {    // Elementti: 26
    Elementti e1 = new Elementti(1, "testi", 2, 3); 
    Elementti e2 = new Elementti(2, "testi2", 5, 1); 
    assertEquals("From: Elementti line: 29", "testi", e1.getNimi()); 
    assertEquals("From: Elementti line: 30", 1, e1.getID()); 
    assertEquals("From: Elementti line: 31", 2, e1.getVahvuusID()); 
    assertEquals("From: Elementti line: 32", 3, e1.getHeikkousID()); 
    assertEquals("From: Elementti line: 33", "testi2", e2.getNimi()); 
    assertEquals("From: Elementti line: 34", 2, e2.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo88 */
  @Test
  public void testCompareTo88() {    // Elementti: 88
    Elementti e1 = new Elementti(1, "testi", 2, 3); 
    Elementti e2 = new Elementti(2, "testi2", 5, 1); 
    Elementti e4 = new Elementti(4, "testi4", 6, 5); 
    assertEquals("From: Elementti line: 92", 1, e1.compareTo(e2)); assertEquals("From: Elementti line: 92", -1, e2.compareTo(e1)); 
    assertEquals("From: Elementti line: 93", 0, e2.compareTo(e4)); assertEquals("From: Elementti line: 93", 0, e4.compareTo(e2)); 
    assertEquals("From: Elementti line: 94", 0, e4.compareTo(e1)); 
  } // Generated by ComTest END
}