package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import java.util.ArrayList;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.29 21:32:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class IatTest {



  // Generated by ComTest BEGIN
  /** testEtsiIka86 */
  @Test
  public void testEtsiIka86() {    // Iat: 86
    Iat i = new Iat(); 
    Ika i1 = new Ika(1, "10-20"); 
    assertEquals("From: Iat line: 89", 0, i.getLkm()); 
    Ika i2 = new Ika(2, "20-30"); 
    i.lisaa(i1); i.lisaa(i2); 
    assertEquals("From: Iat line: 92", i2, i.etsiIka(2)); 
    assertEquals("From: Iat line: 93", i2.getID() - 1, i.etsiIka(1).getID()); 
    assertEquals("From: Iat line: 94", 2, i.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta111 
   * @throws IOException when error
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta111() throws IOException, SailoException {    // Iat: 111
    String tiedosto = "iatTest.dat"; 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
    VertaaTiedosto.kirjoitaTiedosto(tiedosto, ";id|ika\n 1 |0-10\n 2 |10-20\n 3 |20-30\n 4 |30-40"); 
    Iat iThrows = new Iat("eiOle"); 
    try {
    iThrows.lueTiedostosta(); 
    fail("Iat: 120 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    Iat i = new Iat(tiedosto); 
    i.lueTiedostosta(); 
    assertEquals("From: Iat line: 123", 4, i.getLkm()); 
    assertEquals("From: Iat line: 124", "0-10", i.etsiIka(1).getIka()); 
    assertEquals("From: Iat line: 125", "10-20", i.etsiIka(2).getIka()); 
    assertEquals("From: Iat line: 126", "30-40", i.etsiIka(4).getIka()); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallenna146 
   * @throws IOException when error
   * @throws SailoException when error
   */
  @Test
  public void testTallenna146() throws IOException, SailoException {    // Iat: 146
    String tiedosto = "iatTest.dat"; 
    String tiedostobak = tiedosto.replace(".dat", ".bak"); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
    VertaaTiedosto.tuhoaTiedosto(tiedostobak); 
    VertaaTiedosto.kirjoitaTiedosto(tiedosto, ";id|ika\n 1 |0-10\n 2 |10-20\n 3 |20-30\n 4 |30-40"); 
    Iat iThrows = new Iat("eiOle"); 
    try {
    iThrows.lueTiedostosta(); 
    fail("Iat: 157 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    Iat i = new Iat(tiedosto); 
    i.lueTiedostosta(); 
    assertEquals("From: Iat line: 160", 4, i.getLkm()); 
    assertEquals("From: Iat line: 161", "0-10", i.etsiIka(1).getIka()); 
    assertEquals("From: Iat line: 162", "10-20", i.etsiIka(2).getIka()); 
    assertEquals("From: Iat line: 163", "30-40", i.etsiIka(4).getIka()); 
    assertEquals("From: Iat line: 164", null, i.etsiIka(5)); 
    i.lisaa(new Ika(5, "testi")); 
    i.tallenna(); 
    Iat iDat = new Iat(tiedosto); iDat.lueTiedostosta(); 
    Iat iBak = new Iat(tiedostobak); iBak.lueTiedostosta(); 
    assertEquals("From: Iat line: 170", "30-40", iDat.etsiIka(4).getIka()); assertEquals("From: Iat line: 170", "30-40", iBak.etsiIka(4).getIka()); 
    assertEquals("From: Iat line: 171", "testi", iDat.etsiIka(5).getIka()); assertEquals("From: Iat line: 171", null, iBak.etsiIka(5)); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
    VertaaTiedosto.tuhoaTiedosto(tiedostobak); 
  } // Generated by ComTest END
}