package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.15 11:25:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class IkaTest {



  // Generated by ComTest BEGIN
  /** testIka24 */
  @Test
  public void testIka24() {    // Ika: 24
    Ika ika1 = new Ika(1, "0-10"); 
    assertEquals("From: Ika line: 26", 1, ika1.getID()); 
    assertEquals("From: Ika line: 27", "0-10", ika1.getIka()); 
    assertEquals("From: Ika line: 28", "0-10", ika1.toString()); 
    Ika ika2 = new Ika(2, "30-40"); 
    assertEquals("From: Ika line: 30", ika1.getID(), ika2.getID() - 1); 
  } // Generated by ComTest END
}