package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static rekisteri.Pokemon.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.27 12:09:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PokemonTest {



  // Generated by ComTest BEGIN
  /** testPokemon50 */
  @Test
  public void testPokemon50() {    // Pokemon: 50
    Pokemon uusi = new Pokemon("3|Uusi|69|2|3|1|8|0|Olen uusi"); 
    assertEquals("From: Pokemon line: 52", "Uusi", uusi.getNimi()); assertEquals("From: Pokemon line: 52", 1, uusi.getElementtiID(2)); 
    assertEquals("From: Pokemon line: 53", 2, uusi.getIkaID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi128 */
  @Test
  public void testRekisteroi128() {    // Pokemon: 128
    Pokemon pikachu = new Pokemon(); 
    Pokemon charizard = new Pokemon(); 
    assertEquals("From: Pokemon line: 131", 0, pikachu.getID()); 
    int n1 = pikachu.rekisteroi(); 
    assertEquals("From: Pokemon line: 133", 0, charizard.getID()); 
    int n2 = charizard.rekisteroi(); 
    assertEquals("From: Pokemon line: 135", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetElementtiID158 */
  @Test
  public void testGetElementtiID158() {    // Pokemon: 158
    Pokemon pikachu = new Pokemon(); 
    pikachu.vastaa_pikachu(); 
    assertEquals("From: Pokemon line: 161", 2, pikachu.getElementtiID(1)); 
    assertEquals("From: Pokemon line: 162", 3, pikachu.getElementtiID(2)); 
    assertEquals("From: Pokemon line: 163", 0, pikachu.getElementtiID(3)); 
    assertEquals("From: Pokemon line: 164", 0, pikachu.getElementtiID(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaNimi188 */
  @Test
  public void testTarkistaNimi188() {    // Pokemon: 188
    assertEquals("From: Pokemon line: 189", true, tarkistaNimi("Pikachu")); 
    assertEquals("From: Pokemon line: 190", false, tarkistaNimi("pikachu")); 
    assertEquals("From: Pokemon line: 191", false, tarkistaNimi("Pikachu ")); 
    assertEquals("From: Pokemon line: 192", false, tarkistaNimi(" Pikachu")); 
    assertEquals("From: Pokemon line: 193", false, tarkistaNimi("Pikachu1")); 
    assertEquals("From: Pokemon line: 194", true, tarkistaNimi("P")); 
    assertEquals("From: Pokemon line: 195", false, tarkistaNimi("")); 
    assertEquals("From: Pokemon line: 196", false, tarkistaNimi("€")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaVahvuus209 */
  @Test
  public void testTarkistaVahvuus209() {    // Pokemon: 209
    assertEquals("From: Pokemon line: 210", false, tarkistaVahvuus(0)); 
    assertEquals("From: Pokemon line: 211", true, tarkistaVahvuus(1)); 
    assertEquals("From: Pokemon line: 212", false, tarkistaVahvuus(-1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaEvoluutio226 */
  @Test
  public void testTarkistaEvoluutio226() {    // Pokemon: 226
    assertEquals("From: Pokemon line: 227", true, tarkistaEvoluutio(2)); 
    assertEquals("From: Pokemon line: 228", false, tarkistaEvoluutio(0)); 
    assertEquals("From: Pokemon line: 229", false, tarkistaEvoluutio(5)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaSeuraavaEvoluutio244 */
  @Test
  public void testTarkistaSeuraavaEvoluutio244() {    // Pokemon: 244
    Pokemon uusi = new Pokemon(); 
    int temp = uusi.rekisteroi(); 
    assertEquals("From: Pokemon line: 247", true, tarkistaSeuraavaEvoluutio(temp)); 
    assertEquals("From: Pokemon line: 248", false, tarkistaSeuraavaEvoluutio(temp+1)); 
    assertEquals("From: Pokemon line: 249", false, tarkistaSeuraavaEvoluutio(0)); 
    assertEquals("From: Pokemon line: 250", false, tarkistaSeuraavaEvoluutio(-1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetElementtienLkm301 */
  @Test
  public void testGetElementtienLkm301() {    // Pokemon: 301
    Pokemon p = new Pokemon(); 
    p.rekisteroi(); p.vastaa_pikachu(); 
    assertEquals("From: Pokemon line: 304", 2, p.getElementtienLkm()); 
    p.setElementtiID(1, 0); 
    assertEquals("From: Pokemon line: 306", 1, p.getElementtienLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString412 */
  @Test
  public void testToString412() {    // Pokemon: 412
    Pokemon uusi = new Pokemon("2|Pika|12|3|1|2|3|0|valiaikainen"); 
    uusi.rekisteroi(); 
    assertEquals("From: Pokemon line: 415", true, uusi.toString().startsWith("2|Pika|12|")); 
    assertEquals("From: Pokemon line: 416", false, uusi.toString().startsWith("2|Aku|12|")); 
  } // Generated by ComTest END
}