package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import java.util.ArrayList;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.26 19:36:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PokemonitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa54 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa54() throws SailoException {    // Pokemonit: 54
    Pokemonit pokemonit = new Pokemonit(); 
    Pokemon pikachu = new Pokemon(), charizard = new Pokemon(); 
    assertEquals("From: Pokemonit line: 58", 0, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 59", 1, pokemonit.getLkm()); 
    pokemonit.lisaa(charizard); assertEquals("From: Pokemonit line: 60", 2, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 61", 3, pokemonit.getLkm()); 
    assertEquals("From: Pokemonit line: 62", pikachu, pokemonit.getPokemon(0)); 
    assertEquals("From: Pokemonit line: 63", charizard, pokemonit.getPokemon(1)); 
    assertEquals("From: Pokemonit line: 64", pikachu, pokemonit.getPokemon(2)); 
    assertEquals("From: Pokemonit line: 65", false, pokemonit.getPokemon(1) == pikachu); 
    assertEquals("From: Pokemonit line: 66", true, pokemonit.getPokemon(1) == charizard); 
    try {
    assertEquals("From: Pokemonit line: 67", pikachu, pokemonit.getPokemon(3)); 
    fail("Pokemonit: 67 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 68", 4, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 69", 5, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); pokemonit.lisaa(pikachu); 
    pokemonit.lisaa(pikachu); 
    pokemonit.lisaa(pikachu); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista99 
   * @throws SailoException when error
   */
  @Test
  public void testPoista99() throws SailoException {    // Pokemonit: 99
    Pokemonit pokemonit = new Pokemonit(); 
    Pokemon pikachu = new Pokemon(); 
    Pokemon charizard = new Pokemon(); 
    Pokemon pikachu2 = new Pokemon(); 
    charizard.vastaa_pikachu(); 
    assertEquals("From: Pokemonit line: 106", 0, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); 
    assertEquals("From: Pokemonit line: 108", 1, pokemonit.getLkm()); 
    pokemonit.lisaa(charizard); 
    assertEquals("From: Pokemonit line: 110", 2, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu2); 
    assertEquals("From: Pokemonit line: 112", 3, pokemonit.getLkm()); 
    assertEquals("From: Pokemonit line: 113", pikachu, pokemonit.getPokemon(0)); 
    assertEquals("From: Pokemonit line: 114", charizard, pokemonit.getPokemon(1)); 
    assertEquals("From: Pokemonit line: 115", pikachu2, pokemonit.getPokemon(2)); 
    pokemonit.poista(charizard.getID()); 
    assertEquals("From: Pokemonit line: 117", 2, pokemonit.getLkm()); 
    assertEquals("From: Pokemonit line: 118", pikachu2, pokemonit.getPokemon(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta162 
   * @throws IOException when error
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta162() throws IOException, SailoException {    // Pokemonit: 162
    String tiedosto = "pokemonitTest.dat"; 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
    VertaaTiedosto.kirjoitaTiedosto(tiedosto, ";ID|Pokemonin nimi|vahvuus |ikä ID|elementti1 |elementti2 |evoluutio |seuraavan evoluution ID|lisatiedot |\n"
    + "1 |Pikachu       |1337    |1     |6          |0          |2         |5                      |    lisätiedot      |\n"
    + "2 |Charizard     |20      |4     |1          |4          |3         |0                      | |"); 
    Pokemonit p = new Pokemonit(tiedosto); 
    p.lueTiedostosta(); 
    assertEquals("From: Pokemonit line: 174", 2, p.getLkm()); 
    assertEquals("From: Pokemonit line: 175", "Pikachu", p.getPokemon(0).getNimi()); 
    assertEquals("From: Pokemonit line: 176", "Charizard", p.getPokemon(1).getNimi()); 
    assertEquals("From: Pokemonit line: 177", 6, p.getPokemon(0).getElementtiID(1)); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallenna207 
   * @throws IOException when error
   * @throws SailoException when error
   */
  @Test
  public void testTallenna207() throws IOException, SailoException {    // Pokemonit: 207
    String tiedosto = "pokemonitTest.dat"; 
    String tiedostobak = "pokemonitTest.bak"; 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
    VertaaTiedosto.tuhoaTiedosto(tiedostobak); 
    VertaaTiedosto.kirjoitaTiedosto(tiedosto, ";ID|Pokemonin nimi|vahvuus |ikä ID|elementti1 |elementti2 |evoluutio |seuraavan evoluution ID|lisatiedot |\n"
    + "1 |Pikachu       |1337    |1     |6          |0          |2         |5                      |   testi        |\n"
    + "2 |Charizard     |20      |4     |1          |4          |3         |0                      |     tesi60     |"); 
    Pokemonit pThrows = new Pokemonit("eiOle"); 
    try {
    pThrows.lueTiedostosta(); 
    fail("Pokemonit: 220 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    Pokemonit p = new Pokemonit(tiedosto); 
    p.lueTiedostosta(); 
    assertEquals("From: Pokemonit line: 223", 2, p.getLkm()); 
    assertEquals("From: Pokemonit line: 224", "Pikachu", p.getPokemon(0).getNimi()); 
    assertEquals("From: Pokemonit line: 225", "Charizard", p.getPokemon(1).getNimi()); 
    Pokemon t = new Pokemon(); 
    t.rekisteroi(); t.vastaa_pikachu(); 
    p.lisaa(t); 
    p.tallenna(); 
    Pokemonit pDat = new Pokemonit(tiedosto); pDat.lueTiedostosta(); 
    Pokemonit pBak = new Pokemonit(tiedostobak); pBak.lueTiedostosta(); 
    assertEquals("From: Pokemonit line: 233", "Pikachu", pDat.getPokemon(0).getNimi()); assertEquals("From: Pokemonit line: 233", "Pikachu", pBak.getPokemon(0).getNimi()); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
    VertaaTiedosto.tuhoaTiedosto(tiedostobak); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsiTaulukosta280 */
  @Test
  public void testEtsiTaulukosta280() {    // Pokemonit: 280
    Pokemonit p = new Pokemonit(); 
    Pokemon t = new Pokemon(); 
    t.rekisteroi(); 
    t.vastaa_pikachu(); p.lisaa(t); 
    assertEquals("From: Pokemonit line: 285", t, p.etsiTaulukosta("pikachu")); 
    assertEquals("From: Pokemonit line: 286", null, p.etsiTaulukosta("pokemon")); 
  } // Generated by ComTest END
}