package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static rekisteri.Pokemon.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.02 14:19:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PokemonTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi76 */
  @Test
  public void testRekisteroi76() {    // Pokemon: 76
    Pokemon pikachu = new Pokemon(); 
    Pokemon charizard = new Pokemon(); 
    assertEquals("From: Pokemon line: 79", 0, pikachu.getID()); 
    int n1 = pikachu.rekisteroi(); 
    assertEquals("From: Pokemon line: 81", 0, charizard.getID()); 
    int n2 = charizard.rekisteroi(); 
    assertEquals("From: Pokemon line: 83", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaNimi106 */
  @Test
  public void testTarkistaNimi106() {    // Pokemon: 106
    assertEquals("From: Pokemon line: 107", true, tarkistaNimi("Pikachu")); 
    assertEquals("From: Pokemon line: 108", false, tarkistaNimi("pikachu")); 
    assertEquals("From: Pokemon line: 109", false, tarkistaNimi("Pikachu ")); 
    assertEquals("From: Pokemon line: 110", false, tarkistaNimi(" Pikachu")); 
    assertEquals("From: Pokemon line: 111", false, tarkistaNimi("Pikachu1")); 
    assertEquals("From: Pokemon line: 112", true, tarkistaNimi("P")); 
    assertEquals("From: Pokemon line: 113", false, tarkistaNimi("")); 
    assertEquals("From: Pokemon line: 114", false, tarkistaNimi("€")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaVahvuus128 */
  @Test
  public void testTarkistaVahvuus128() {    // Pokemon: 128
    assertEquals("From: Pokemon line: 129", false, tarkistaVahvuus(0)); 
    assertEquals("From: Pokemon line: 130", true, tarkistaVahvuus(1)); 
    assertEquals("From: Pokemon line: 131", false, tarkistaVahvuus(-1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaEvoluutio144 */
  @Test
  public void testTarkistaEvoluutio144() {    // Pokemon: 144
    assertEquals("From: Pokemon line: 145", true, tarkistaEvoluutio(2)); 
    assertEquals("From: Pokemon line: 146", false, tarkistaEvoluutio(0)); 
    assertEquals("From: Pokemon line: 147", false, tarkistaEvoluutio(5)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaSeuraavaEvoluutio160 */
  @Test
  public void testTarkistaSeuraavaEvoluutio160() {    // Pokemon: 160
    Pokemon uusi = new Pokemon(); 
    int temp = uusi.rekisteroi(); 
    assertEquals("From: Pokemon line: 163", true, tarkistaSeuraavaEvoluutio(temp)); 
    assertEquals("From: Pokemon line: 164", false, tarkistaSeuraavaEvoluutio(temp+1)); 
    assertEquals("From: Pokemon line: 165", false, tarkistaSeuraavaEvoluutio(0)); 
    assertEquals("From: Pokemon line: 166", false, tarkistaSeuraavaEvoluutio(-1)); 
  } // Generated by ComTest END
}