package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 12:15:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PokemonitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa42 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa42() throws SailoException {    // Pokemonit: 42
    Pokemonit pokemonit = new Pokemonit(); 
    Pokemon pikachu = new Pokemon(), charizard = new Pokemon(); 
    assertEquals("From: Pokemonit line: 46", 0, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 47", 1, pokemonit.getLkm()); 
    pokemonit.lisaa(charizard); assertEquals("From: Pokemonit line: 48", 2, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 49", 3, pokemonit.getLkm()); 
    assertEquals("From: Pokemonit line: 50", pikachu, pokemonit.getPokemon(0)); 
    assertEquals("From: Pokemonit line: 51", charizard, pokemonit.getPokemon(1)); 
    assertEquals("From: Pokemonit line: 52", pikachu, pokemonit.getPokemon(2)); 
    assertEquals("From: Pokemonit line: 53", false, pokemonit.getPokemon(1) == pikachu); 
    assertEquals("From: Pokemonit line: 54", true, pokemonit.getPokemon(1) == charizard); 
    try {
    assertEquals("From: Pokemonit line: 55", pikachu, pokemonit.getPokemon(3)); 
    fail("Pokemonit: 55 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 56", 4, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 57", 5, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); pokemonit.lisaa(pikachu); 
    pokemonit.lisaa(pikachu); 
    pokemonit.lisaa(pikachu); 
  } // Generated by ComTest END
}