package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static rekisteri.Pokemon.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 12:04:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PokemonTest {



  // Generated by ComTest BEGIN
  /** testPokemon50 */
  @Test
  public void testPokemon50() {    // Pokemon: 50
    Pokemon uusi = new Pokemon("3|Uusi|69|2|3|1|8|Olen uusi"); 
    assertEquals("From: Pokemon line: 52", "Uusi", uusi.getNimi()); assertEquals("From: Pokemon line: 52", 1, uusi.getElementtiID(2)); 
    assertEquals("From: Pokemon line: 53", 2, uusi.getIkaID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi127 */
  @Test
  public void testRekisteroi127() {    // Pokemon: 127
    Pokemon pikachu = new Pokemon(); 
    Pokemon charizard = new Pokemon(); 
    assertEquals("From: Pokemon line: 130", 0, pikachu.getID()); 
    int n1 = pikachu.rekisteroi(); 
    assertEquals("From: Pokemon line: 132", 0, charizard.getID()); 
    int n2 = charizard.rekisteroi(); 
    assertEquals("From: Pokemon line: 134", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetElementtiID157 */
  @Test
  public void testGetElementtiID157() {    // Pokemon: 157
    Pokemon pikachu = new Pokemon(); 
    pikachu.vastaa_pikachu(); 
    assertEquals("From: Pokemon line: 160", 2, pikachu.getElementtiID(1)); 
    assertEquals("From: Pokemon line: 161", 3, pikachu.getElementtiID(2)); 
    assertEquals("From: Pokemon line: 162", 0, pikachu.getElementtiID(3)); 
    assertEquals("From: Pokemon line: 163", 0, pikachu.getElementtiID(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaNimi187 */
  @Test
  public void testTarkistaNimi187() {    // Pokemon: 187
    assertEquals("From: Pokemon line: 188", true, tarkistaNimi("Pikachu")); 
    assertEquals("From: Pokemon line: 189", false, tarkistaNimi("pikachu")); 
    assertEquals("From: Pokemon line: 190", false, tarkistaNimi("Pikachu ")); 
    assertEquals("From: Pokemon line: 191", false, tarkistaNimi(" Pikachu")); 
    assertEquals("From: Pokemon line: 192", false, tarkistaNimi("Pikachu1")); 
    assertEquals("From: Pokemon line: 193", true, tarkistaNimi("P")); 
    assertEquals("From: Pokemon line: 194", false, tarkistaNimi("")); 
    assertEquals("From: Pokemon line: 195", false, tarkistaNimi("€")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaVahvuus208 */
  @Test
  public void testTarkistaVahvuus208() {    // Pokemon: 208
    assertEquals("From: Pokemon line: 209", false, tarkistaVahvuus(0)); 
    assertEquals("From: Pokemon line: 210", true, tarkistaVahvuus(1)); 
    assertEquals("From: Pokemon line: 211", false, tarkistaVahvuus(-1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaEvoluutio225 */
  @Test
  public void testTarkistaEvoluutio225() {    // Pokemon: 225
    assertEquals("From: Pokemon line: 226", true, tarkistaEvoluutio(2)); 
    assertEquals("From: Pokemon line: 227", false, tarkistaEvoluutio(0)); 
    assertEquals("From: Pokemon line: 228", false, tarkistaEvoluutio(5)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaSeuraavaEvoluutio243 */
  @Test
  public void testTarkistaSeuraavaEvoluutio243() {    // Pokemon: 243
    Pokemon uusi = new Pokemon(); 
    int temp = uusi.rekisteroi(); 
    assertEquals("From: Pokemon line: 246", true, tarkistaSeuraavaEvoluutio(temp)); 
    assertEquals("From: Pokemon line: 247", false, tarkistaSeuraavaEvoluutio(temp+1)); 
    assertEquals("From: Pokemon line: 248", false, tarkistaSeuraavaEvoluutio(0)); 
    assertEquals("From: Pokemon line: 249", false, tarkistaSeuraavaEvoluutio(-1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString280 */
  @Test
  public void testToString280() {    // Pokemon: 280
    Pokemon uusi = new Pokemon("2|Pika|12|3|1|2|3|0|valiaikainen"); 
    uusi.rekisteroi(); 
    assertEquals("From: Pokemon line: 283", true, uusi.toString().startsWith("2|Pika|12|")); 
    assertEquals("From: Pokemon line: 284", false, uusi.toString().startsWith("2|Aku|12|")); 
  } // Generated by ComTest END
}