package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import java.util.ArrayList;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 14:11:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PokemonitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa52 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa52() throws SailoException {    // Pokemonit: 52
    Pokemonit pokemonit = new Pokemonit(); 
    Pokemon pikachu = new Pokemon(), charizard = new Pokemon(); 
    assertEquals("From: Pokemonit line: 56", 0, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 57", 1, pokemonit.getLkm()); 
    pokemonit.lisaa(charizard); assertEquals("From: Pokemonit line: 58", 2, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 59", 3, pokemonit.getLkm()); 
    assertEquals("From: Pokemonit line: 60", pikachu, pokemonit.getPokemon(0)); 
    assertEquals("From: Pokemonit line: 61", charizard, pokemonit.getPokemon(1)); 
    assertEquals("From: Pokemonit line: 62", pikachu, pokemonit.getPokemon(2)); 
    assertEquals("From: Pokemonit line: 63", false, pokemonit.getPokemon(1) == pikachu); 
    assertEquals("From: Pokemonit line: 64", true, pokemonit.getPokemon(1) == charizard); 
    try {
    assertEquals("From: Pokemonit line: 65", pikachu, pokemonit.getPokemon(3)); 
    fail("Pokemonit: 65 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 66", 4, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); assertEquals("From: Pokemonit line: 67", 5, pokemonit.getLkm()); 
    pokemonit.lisaa(pikachu); pokemonit.lisaa(pikachu); 
    pokemonit.lisaa(pikachu); 
    pokemonit.lisaa(pikachu); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta119 
   * @throws IOException when error
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta119() throws IOException, SailoException {    // Pokemonit: 119
    String tiedosto = "pokemonitTest.dat"; 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
    VertaaTiedosto.kirjoitaTiedosto(tiedosto, ";ID|Pokemonin nimi|vahvuus |ikä ID|elementti1 |elementti2 |evoluutio |seuraavan evoluution ID|lisatiedot |\n"
    + "1 |Pikachu       |1337    |1     |6          |0          |2         |5                      |           |\n"
    + "2 |Charizard     |20      |4     |1          |4          |3         |0                      |           |"); 
    Pokemonit p = new Pokemonit(tiedosto); 
    p.lueTiedostosta(); 
    assertEquals("From: Pokemonit line: 131", 2, p.getLkm()); 
    assertEquals("From: Pokemonit line: 132", "Pikachu", p.getPokemon(0).getNimi()); 
    assertEquals("From: Pokemonit line: 133", "Charizard", p.getPokemon(1).getNimi()); 
    assertEquals("From: Pokemonit line: 134", 6, p.getPokemon(0).getElementtiID(1)); 
    VertaaTiedosto.tuhoaTiedosto(tiedosto); 
  } // Generated by ComTest END
}