package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.29 19:55:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** testLisaa65 */
  @Test
  public void testLisaa65() {    // Rekisteri: 65
    Rekisteri rekisteri = new Rekisteri(); 
    Pokemon pikachu = new Pokemon(), charizard = new Pokemon(); 
    assertEquals("From: Rekisteri line: 68", 0, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 69", 1, rekisteri.getLkm()); 
    rekisteri.lisaa(charizard); assertEquals("From: Rekisteri line: 70", 2, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 71", 3, rekisteri.getLkm()); 
    assertEquals("From: Rekisteri line: 72", pikachu, rekisteri.getPokemon(0)); 
    assertEquals("From: Rekisteri line: 73", charizard, rekisteri.getPokemon(1)); 
    assertEquals("From: Rekisteri line: 74", pikachu, rekisteri.getPokemon(2)); 
    assertEquals("From: Rekisteri line: 75", false, rekisteri.getPokemon(1) == pikachu); 
    assertEquals("From: Rekisteri line: 76", true, rekisteri.getPokemon(1) == charizard); 
    assertEquals("From: Rekisteri line: 77", pikachu, rekisteri.getPokemon(2)); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 78", 4, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 79", 5, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); rekisteri.lisaa(pikachu); 
    rekisteri.lisaa(pikachu); 
    rekisteri.lisaa(pikachu); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testElementitJonona170 */
  @Test
  public void testElementitJonona170() {    // Rekisteri: 170
    Rekisteri r = new Rekisteri(); 
    r.getElementit().alustaElementeilla(); 
    Pokemon p = new Pokemon(); 
    p.vastaa_pikachu(); 
    assertEquals("From: Rekisteri line: 175", "tuli + maa", r.elementitJonona(p)); 
    p.asetaTyhjaElementti(); 
    assertEquals("From: Rekisteri line: 177", "tuli", r.elementitJonona(p)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaElementti200 */
  @Test
  public void testAnnaElementti200() {    // Rekisteri: 200
    Rekisteri r = new Rekisteri(); 
    r.getElementit().alustaElementeilla(); 
    Pokemon p = new Pokemon(); 
    p.vastaa_pikachu(); 
    assertEquals("From: Rekisteri line: 205", "tuli", r.annaElementti(p, 1)); 
    assertEquals("From: Rekisteri line: 206", "maa", r.annaElementti(p, 2)); 
    assertEquals("From: Rekisteri line: 207", "", r.annaElementti(p, 5)); 
  } // Generated by ComTest END
}