package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.02 15:32:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa29 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa29() throws SailoException {    // Rekisteri: 29
    Rekisteri rekisteri = new Rekisteri(); 
    Pokemon pikachu = new Pokemon(), charizard = new Pokemon(); 
    assertEquals("From: Rekisteri line: 33", 0, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 34", 1, rekisteri.getLkm()); 
    rekisteri.lisaa(charizard); assertEquals("From: Rekisteri line: 35", 2, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 36", 3, rekisteri.getLkm()); 
    assertEquals("From: Rekisteri line: 37", pikachu, rekisteri.getPokemon(0)); 
    assertEquals("From: Rekisteri line: 38", charizard, rekisteri.getPokemon(1)); 
    assertEquals("From: Rekisteri line: 39", pikachu, rekisteri.getPokemon(2)); 
    assertEquals("From: Rekisteri line: 40", false, rekisteri.getPokemon(1) == pikachu); 
    assertEquals("From: Rekisteri line: 41", true, rekisteri.getPokemon(1) == charizard); 
    try {
    assertEquals("From: Rekisteri line: 42", pikachu, rekisteri.getPokemon(3)); 
    fail("Rekisteri: 42 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 43", 4, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 44", 5, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); rekisteri.lisaa(pikachu); 
    rekisteri.lisaa(pikachu); 
    try {
    rekisteri.lisaa(pikachu); 
    fail("Rekisteri: 47 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}