package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.15 11:43:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa43 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa43() throws SailoException {    // Rekisteri: 43
    Rekisteri rekisteri = new Rekisteri(); 
    Pokemon pikachu = new Pokemon(), charizard = new Pokemon(); 
    assertEquals("From: Rekisteri line: 47", 0, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 48", 1, rekisteri.getLkm()); 
    rekisteri.lisaa(charizard); assertEquals("From: Rekisteri line: 49", 2, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 50", 3, rekisteri.getLkm()); 
    assertEquals("From: Rekisteri line: 51", pikachu, rekisteri.getPokemon(0)); 
    assertEquals("From: Rekisteri line: 52", charizard, rekisteri.getPokemon(1)); 
    assertEquals("From: Rekisteri line: 53", pikachu, rekisteri.getPokemon(2)); 
    assertEquals("From: Rekisteri line: 54", false, rekisteri.getPokemon(1) == pikachu); 
    assertEquals("From: Rekisteri line: 55", true, rekisteri.getPokemon(1) == charizard); 
    try {
    assertEquals("From: Rekisteri line: 56", pikachu, rekisteri.getPokemon(3)); 
    fail("Rekisteri: 56 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 57", 4, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); assertEquals("From: Rekisteri line: 58", 5, rekisteri.getLkm()); 
    rekisteri.lisaa(pikachu); rekisteri.lisaa(pikachu); 
    rekisteri.lisaa(pikachu); 
    try {
    rekisteri.lisaa(pikachu); 
    fail("Rekisteri: 61 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testElementitJonona156 */
  @Test
  public void testElementitJonona156() {    // Rekisteri: 156
    Rekisteri r = new Rekisteri(); 
    r.getElementit().alustaElementeilla(); 
    Pokemon p = new Pokemon(); 
    p.vastaa_pikachu(); 
    assertEquals("From: Rekisteri line: 161", "Elementit: tuli maa", r.elementitJonona(p)); 
    p.asetaTyhjaElementti(); 
    assertEquals("From: Rekisteri line: 163", "Elementit: tuli ", r.elementitJonona(p)); 
  } // Generated by ComTest END
}